services:
  cancel-search:
    image: 10.8.44.151:5000/cancel-search:release
    container_name: cancel-search
    ports:
      - "8080:8080"
    env_file:
      - cancel-search/.env
  cancel-search-cc:
    image: 10.8.44.151:5000/cancel-search-cc:release
    container_name: cancel-search-cc
    ports:
      - "8079:8079"
    env_file:
      - cancel-search-cc/.env
  toilet-feedback:
    image: 10.8.44.151:5000/toilet-feedback:beta
    container_name: toilet-feedback
    ports:
      - "6003:6003"
    env_file:
      - toilet-feedback/.env
