host: 10.8.41.142:8079
info:
  contact:
    email: hsakira.k861@mmh.org.tw
    name: 李承洋/K861
  description: 刪除預約掛號查詢表格(竹兒)
  license:
    name: Private/馬偕紀念醫院 員工保密協定
  title: cancel-search-cc
  version: 24.04r2
paths:
  /search/del/{pno}:
    get:
      description: 輸入病歷號碼來獲取取消掛號紀錄
      parameters:
      - description: 病歷號碼
        in: query
        name: pno
        required: true
        type: string
      produces:
      - application/x-www-form-urlencoded
      responses: {}
      summary: GetDelRecord
      tags:
      - Search PatientService
  /search/id/{idno}:
    get:
      description: 輸入病歷號碼，取得病歷號、姓名、性別、生日、身分證字號
      parameters:
      - description: 病歷號碼
        in: query
        name: idno
        required: true
        type: string
      produces:
      - application/x-www-form-urlencoded
      responses: {}
      summary: GetPatientInfoViaPno
      tags:
      - Search
schemes:
- http
swagger: "2.0"
