// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "李承洋/K861",
            "email": "hsakira.k861@mmh.org.tw"
        },
        "license": {
            "name": "Private/馬偕紀念醫院 員工保密協定"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sms": {
            "post": {
                "description": "傳送簡訊",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/x-www-form-urlencoded"
                ],
                "tags": [
                    "Write\tSMS"
                ],
                "summary": "SMSSend",
                "parameters": [
                    {
                        "description": "電話號碼、簡訊內容",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SMSData"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.SMSData": {
            "type": "object",
            "required": [
                "message",
                "oper",
                "phsno",
                "udate"
            ],
            "properties": {
                "kind": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "oper": {
                    "type": "string"
                },
                "phsno": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "udate": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "24.08b3",
	Host:             "10.8.41.142:6003",
	BasePath:         "",
	Schemes:          []string{"http"},
	Title:            "toilet-feedback",
	Description:      "公共區域通報系統",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
