definitions:
  models.FeedBackFormat:
    properties:
      an_Code:
        type: string
      an_Cout1:
        type: string
      an_Cout2:
        type: string
      an_Cout3:
        type: string
      an_Cout4:
        type: string
      an_Cout5:
        type: string
      an_Cout6:
        type: string
      an_Name:
        type: string
    required:
    - an_Code
    - an_Cout1
    - an_Cout2
    - an_Cout3
    - an_Cout4
    - an_Cout5
    - an_Cout6
    - an_Name
    type: object
host: 10.8.41.142:6003
info:
  contact:
    email: hsakira.k861@mmh.org.tw
    name: 李承洋/K861
  description: 公共區域通報系統
  license:
    name: Private/馬偕紀念醫院 員工保密協定
  title: toilet-feedback
  version: 24.07b1
paths:
  /ins/ins:
    post:
      consumes:
      - application/json
      description: 輸入通報資料
      parameters:
      - description: 由上而下值為：問卷代號(請全部大寫)、項目代碼、答案、病歷號碼
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.FeedBackFormat'
      produces:
      - application/x-www-form-urlencoded
      responses: {}
      summary: MannouInsert
      tags:
      - Insert
schemes:
- http
swagger: "2.0"
