definitions:
  models.SMSData:
    properties:
      kind:
        type: string
      message:
        type: string
      oper:
        type: string
      phsno:
        type: string
      status:
        type: string
      udate:
        type: string
    required:
    - message
    - oper
    - phsno
    - udate
    type: object
host: 10.8.41.142:6003
info:
  contact:
    email: hsakira.k861@mmh.org.tw
    name: 李承洋/K861
  description: 公共區域通報系統
  license:
    name: Private/馬偕紀念醫院 員工保密協定
  title: toilet-feedback
  version: 24.08b3
paths:
  /sms:
    post:
      consumes:
      - application/json
      description: 傳送簡訊
      parameters:
      - description: 電話號碼、簡訊內容
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SMSData'
      produces:
      - application/x-www-form-urlencoded
      responses: {}
      summary: SMSSend
      tags:
      - "Write\tSMS"
schemes:
- http
swagger: "2.0"
