host: 10.8.41.142:8080
info:
  contact:
    email: hsakira.k861@mmh.org.tw
    name: 李承洋/K861
  description: 刪除預約掛號查詢表格
  license:
    name: Private/馬偕紀念醫院 員工保密協定
  title: cancel-search
  version: 24.04r2
paths:
  /search/del/{pno}:
    get:
      description: 輸入病歷號碼來獲取取消掛號紀錄
      parameters:
      - description: 病歷號碼
        in: query
        name: pno
        required: true
        type: string
      produces:
      - application/x-www-form-urlencoded
      responses: {}
      summary: GetDelRecord
      tags:
      - Search PatientService
schemes:
- http
swagger: "2.0"
